alias: Освежитель воздуха - Пись-как
description: ''
trigger:
  - platform: state
    entity_id:
      - switch.home_toilet_switch
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 2
      seconds: 0
condition: []
action:
  - wait_for_trigger:
      - platform: state
        entity_id:
          - switch.home_toilet_switch
        from: 'on'
        to: 'off'
  - service: button.press
    data: {}
    target:
      entity_id: button.home_toilet_airfreshener_button_turbo
mode: restart
