alias: Освежитель воздуха - Не пшикать когда туалет занят
description: ''
trigger:
  - platform: state
    entity_id:
      - switch.home_toilet_switch
    to: 'on'
    from: 'off'
condition: []
action:
  - service: mqtt.publish
    data:
      topic: >-
        esphome/home/toilet/airfreshener/button/home_toilet_airfreshener_button/command
      retain: true
      payload: ''
  - service: mqtt.publish
    data:
      topic: >-
        esphome/home/toilet/airfreshener/button/home_toilet_airfreshener_button_turbo/command
      retain: true
      payload: ''
mode: single
