alias: Освежитель воздуха - Не пшикать если включен запрет сна
description: ''
trigger:
  - platform: mqtt
    topic: >-
      esphome/home/toilet/airfreshener/button/home_toilet_airfreshener_deepsleep_stop/command
    payload: PRESS
condition: []
action:
  - service: mqtt.publish
    data:
      topic: >-
        esphome/home/toilet/airfreshener/button/home_toilet_airfreshener_button/command
      retain: true
      payload: ''
  - service: mqtt.publish
    data:
      topic: >-
        esphome/home/toilet/airfreshener/button/home_toilet_airfreshener_button_turbo/command
      retain: true
      payload: ''
mode: single
