alias: MQTT - Статус ночи
description: ''
trigger:
  - platform: state
    entity_id:
      - binary_sensor.night
condition: []
action:
  - service: mqtt.publish
    data:
      topic: mqtt/night
      payload: >
        {% if (states('binary_sensor.night')) == 'on' %} ON {% else %} {% endif
        %}
      retain: true
mode: single
