mqtt:
  button:
    - unique_id: home_toilet_airfreshener_button
      name: 'Пшик освежителем'
      icon: mdi:spray
      command_topic: 'esphome/home/toilet/airfreshener/button/home_toilet_airfreshener_button/command'
      retain: true

    - unique_id: home_toilet_airfreshener_button_turbo
      name: 'Пшик освежителем 3x'
      icon: mdi:spray
      command_topic: 'esphome/home/toilet/airfreshener/button/home_toilet_airfreshener_button_turbo/command'
      retain: true

    - unique_id: home_toilet_airfreshener_deepsleep_stop
      name: 'Запрет сна'
      icon: mdi:sleep-off
      command_topic: 'esphome/home/toilet/airfreshener/button/home_toilet_airfreshener_deepsleep_stop/command'
      retain: true

    - unique_id: home_toilet_airfreshener_button_count_reset
      name: 'Замена баллона'
      icon: mdi:restore-alert
      command_topic: 'esphome/home/toilet/airfreshener/home_toilet_airfreshener_button_count_reset/command'
      retain: true

binary_sensor:
  - platform: tod
    name: night
    after: '03:00'
    before: '07:00'